# Generated by Django 5.1.1 on 2024-09-20 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='123', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activationcode_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ActivationCode',
                'verbose_name_plural': 'ActivationCodes',
                'db_table': 'ActivationCode',
            },
        ),
    ]
