# Generated by Django 5.1.1 on 2024-09-21 09:02

import utils.generation_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.CharField(default=utils.generation_code.generate_code, max_length=20),
        ),
    ]
