# Generated by Django 5.1.1 on 2024-09-22 18:54

import django.db.models.deletion
import django.utils.timezone
import utils.generation_code
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_product_is_out_of_stock_product_number_of_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utils.generation_code.generate_code, max_length=20)),
                ('order_state', models.CharField(choices=[('recieved', 'recieved'), ('processed', 'processed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='recieved', max_length=100)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail_order', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdetail_product', to='products.product')),
            ],
            options={
                'verbose_name': 'orderdetail',
                'verbose_name_plural': 'orderdetails',
                'db_table': 'OrderDetail',
            },
        ),
    ]
