# Generated by Django 5.1.1 on 2024-09-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_delivery_time_cartorder_cart_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='cart_delivery_time',
        ),
    ]
