# Generated by Django 5.1.1 on 2024-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_cartorder_cart_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderdetail',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
