# Generated by Django 5.1.1 on 2024-09-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cartorderdetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderdetail',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
