# Generated by Django 5.1.1 on 2024-09-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cartorderdetail_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='cart_order_time',
        ),
    ]
