# Generated by Django 5.1.1 on 2024-09-25 09:50

import utils.generation_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_cartorder_cart_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_coupon', models.CharField(default=utils.generation_code.generate_code, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'db_table': 'Coupon',
            },
        ),
    ]
