# Generated by Django 5.1.1 on 2024-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_value',
            field=models.FloatField(default=0),
        ),
    ]
