# Generated by Django 5.1.1 on 2024-09-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/default_image/def.jpg', upload_to='product/'),
        ),
    ]
