# Generated by Django 5.1.1 on 2024-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/default_image/def.jpg', upload_to='category_images/'),
        ),
    ]
